### ISSUE TITLE
[BUG] QR code symbol recognition issue

### ISSUE THREAD

**Issue by FrenkyDema** [FrenkyDema/qrcode_barcode_scanner#11]
# Issue: Problem with QR code reading

## Problem description

During the scanning of a QR code, the software is reading the symbol "[" instead of "{", and the symbol ";" instead of ":", causing an incorrect reading and malfunctioning of the application.

## Steps to reproduce the problem

1. Scan the QR code with the application.
2. Verify the reading of the symbol "[" instead of "{" and the symbol ";" instead of ":".
3. Observe the malfunction of the application.

## Expected behavior

The software should correctly read the symbols "{" and ":", and function properly during the scanning of the QR code.

## Current behavior

The software is reading the symbol "[" instead of "{", and the symbol ";" instead of ":", during the scanning of the QR code, causing a malfunction of the application.

## Possible solution

Modify the code that handles the QR code reading to correctly recognize the symbols "{" and ":" and read them accurately.

**Comment by FrenkyDema** [comment]
# Issue: QR code reading issue with special character combinations

## Problem description

The QR code reading software was not recognizing the correct special character combinations, resulting in the incorrect reading of the "{" symbol as "[" and the ":" symbol as ";". This caused the application to malfunction during the scanning of the QR code.

## Steps to reproduce the problem

1. Scan the QR code with the application.
2. Observe the incorrect reading of the symbols "{" as "[" and ":" as ";".
3. Notice the malfunction of the application.

## Expected behavior

The software should correctly read the symbols "{" and ":" by recognizing their respective special character combinations, and function properly during the scanning of the QR code.

## Current behavior

The software was not recognizing the special character combinations of "{" and ":" during the scanning of the QR code, resulting in the incorrect reading of the symbols and causing the application to malfunction.

## Solution

The issue was resolved by updating the QR code reading function to properly recognize and interpret special character combinations. Specifically, the function was modified to handle the special character combinations of "{" and ":" accurately, which prevented the application from malfunctioning during the scanning of the QR code.

**Comment by receparda71** [comment]
Hello FrenkyDema, when I read a qrcode, if there is a  ('cs') character in the qrcode, it deletes it and brings the missing code.
