### ISSUE TITLE
[BUG] Can't Handle "_"

### ISSUE THREAD

**Issue by m-pastuszek** [FrenkyDema/qrcode_barcode_scanner#31]
**Describe the bug**
Scanned barcode data is incorrect, due to (I think) shift key issue. My barcode contains underscores `_`, but are read as `-`.
When I scan `4000_TRA_TRAILER02` it returns `4000-tra-traileR02`.

**To Reproduce**
Just scan the barcode code128 `4000_TRA_TRAILER02`.

**Expected behavior**
Scanned `4000_TRA_TRAILER02` barcode should return the same data.

**Smartphone (please complete the following information):**

- Device: Pixel 5
- OS: Android 13

**Additional context**
Same scanned barcode in for example, notes app returns correct data, so I think that it may be an issue with reading keyevents.
Tried with two different scanners and both returning incorrect data.

**Comment by m-pastuszek** [comment]
It's not just the issue with underscore character, but also uppercase letters. 
As I said, `4000_TRA_TRAILER02` returns `4000-tra-traileR02` string.

**Comment by FrenkyDema** [comment]
@m-pastuszek  I try with this:
![image](https://github.com/FrenkyDema/qrcode_barcode_scanner/assets/67586090/d7793f34-50ec-4768-8e76-6bbf825c3554)

And it work:
![Screenshot 2023-09-13 alle 08 57 00](https://github.com/FrenkyDema/qrcode_barcode_scanner/assets/67586090/0e8d3d29-a023-4e4b-9f79-98f12f0680b5)

**Comment by m-pastuszek** [comment]
For mine, it don't... Maybe it's related with scanner device.
I've tested Zebra DS2278 and Inateck BCST-70.

![Screenshot_20230914-134443](https://github.com/FrenkyDema/qrcode_barcode_scanner/assets/32341770/9b5d9bb0-83be-494e-bc78-d0d60f13dbbc)

If I change transmission speed to 16ms (from default 0ms), it reads correctly, but then it also causes that sometimes it overrides the output partially.

Please see attached video:

https://github.com/FrenkyDema/qrcode_barcode_scanner/assets/32341770/f84f92e4-a144-4241-b7a9-ddd4e64c8fd0

First scan with Zebra - output `4000-tra-traileR02`.
Second scan with  BCST-70 (correct output).
Third and next scans also with BCST-70, but output is overrided.

Overriding issue: Maybe some buffer variable would be needed?
Wrong output: Looks like that scanner gives too speed events and Android can't read it properly.

**Comment by FrenkyDema** [comment]
@m-pastuszek I should have solved the problem of scan with the new version, let me know if the problem persists
